services:
  app:
    container_name: user-api-service
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB: user
      DB_USER: alex
      DB_PASSWORD: alexsecret
    networks:
      user-network:
    depends_on:
      - db
      - redis
      - nats

  db:
    container_name: mysql
    image: mysql:9.0.0
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - user-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: alex
      MYSQL_PASSWORD: alexsecret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      user-network:

  nats:
    image: nats
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"
    networks: [ "nats" ]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - user-data:/data
    networks:
      - user-network

networks:
  user-network:
    driver: "bridge"
  nats:
    name: nats

volumes:
  user-data:
