name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Install dependencies
      run: |
        go version
        go install honnef.co/go/tools/cmd/staticcheck@latest

      # Run build of the application
    - name: Run build
      run: go build ./...

      # Run vet & lint on the code
    - name: Run vet & lint
      uses: dominikh/staticcheck-action@v1.2.0
      run: |
        go vet .

    - name: Test
      run: go test -v ./...


