name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Go Format
      run: gofmt -s -w .

    - name: Go Vet
      run: go vet ./...

    - name: Install dependencies
      run: go get ./...
      env:
        GOPATH: /home/runner/work/user-api-service/

    - name: Build
      run: go build -v ./...
      env:
        GOPATH: /home/runner/work/user-api-service/

    - name: Test
      run: go test -v ./...
      env:
        GOPATH: /home/runner/work/user-api-service/

